"""Memory protocol, MemoryItem and MemoryKind taxonomy."""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Protocol, runtime_checkable


class MemoryKind(str, Enum):
    SHORT_TERM = "short_term"
    WORKING = "working"
    EPISODIC = "episodic"
    SEMANTIC = "semantic"
    PROCEDURAL = "procedural"
    POLICY = "policy"
    TOOL = "tool"


@dataclass
class MemoryItem:
    """A single stored memory with its content, kind and metadata.

    Attributes:
        content: The text held by the item.
        kind: The memory taxonomy category the item belongs to.
        metadata: Arbitrary structured data attached to the item.
        id: Short hex identifier, generated by default.
        timestamp: Creation time as a Unix timestamp.
    """

    content: str
    kind: MemoryKind
    metadata: dict[str, Any] = field(default_factory=dict)
    id: str = field(default_factory=lambda: uuid.uuid4().hex[:8])
    timestamp: float = field(default_factory=time.time)


@runtime_checkable
class Memory(Protocol):
    def add(self, item: MemoryItem) -> None:
        """Store a memory item."""
        ...

    def query(self, q: str, k: int = 5) -> list[MemoryItem]:
        """Return up to k memory items relevant to the query q."""
        ...
