# SPDX-License-Identifier: Apache-2.0
"""Build notebooks/appendix_D_reproducing_artifacts.ipynb (App D) with nbformat.

CPU-only: this only assembles the .ipynb JSON. It does NOT execute any cell --
no GPU, no Qwen, no store training. App D's listings document the reproduction
pipeline (build_store.py + the build_nb_*.py notebook builders + the data layout)
and verify, against the *shipped* store, that a fresh clone reproduces the
corpus facts byte-exact. The single store-touching cell loads the trained store
on CPU (cheap); the lead runs the full rebuild in CI.

Run:  python scripts/build_nb_appendix_D.py
"""

from __future__ import annotations

import os

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, os.pardir, "notebooks",
                   "appendix_D_reproducing_artifacts.ipynb")

# ---------------------------------------------------------------------------
# Cell sources. Each is copied verbatim into appendix_D_reproducing_artifacts.tex.
# ---------------------------------------------------------------------------

BOOTSTRAP = (
    "import os, sys\n"
    'KNOWLYTIX_SRC = os.environ.get("KNOWLYTIX_SRC", "")\n'
    "if KNOWLYTIX_SRC:\n"
    "    sys.path.insert(0, KNOWLYTIX_SRC)"
)

LAYOUT = '''\
# The reproducible artifact tree. Everything a reader needs to rebuild the book
# is checked in; nothing here is generated by hand.
#
#   gms-rag-tutorial/
#     pyproject.toml                 # deps: knowlytix, torch, transformers, pandas, jupyter
#     scripts/
#       _bootstrap.py                # knowlytix/forgeloop resolve from the installed wheels
#       build_store.py               # corpus  -> trained store + data/corpus_facts.md
#       build_nb_*.py                # one builder per chapter -> notebooks/*.ipynb
#       build_nb_appendix_D.py       # this appendix's builder
#     data/
#       annual_report.md             # the corpus (source of truth for content)
#       corpus_facts.md              # ground-truth facts sheet (generated)
#       eval_cohort.json             # labeled evaluation questions
#       gms_annual_report_store/     # the trained GMS store (generated)
#     notebooks/                     # one runnable .ipynb per chapter
#     book/                          # the LaTeX manuscript
#
# Two kinds of files live in data/: hand-authored inputs (annual_report.md,
# eval_cohort.json) and generated outputs (corpus_facts.md, the store). Generated
# outputs are committed so the book is runnable from a fresh clone without a GPU;
# build_store.py regenerates them byte-for-byte.
import os

REPO_ROOT = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
for sub in ("data/annual_report.md", "data/eval_cohort.json",
            "data/gms_annual_report_store", "scripts/build_store.py"):
    path = os.path.join(REPO_ROOT, sub)
    print(f"{'OK ' if os.path.exists(path) else 'MISSING':8} {sub}")'''

STORE_LAYOUT = '''\
# The trained store is a directory of small artifacts -- a model checkpoint, an
# adapter, the ENM table, and the source markdown. It is portable: copy the
# directory and the store loads anywhere, no retraining. This is what build_store.py
# writes and what every chapter reloads.
STORE = os.path.join(REPO_ROOT, "data", "gms_annual_report_store")
for name in sorted(os.listdir(STORE)):
    print(name)'''

BUILD_STORE_DOC = '''\
# scripts/build_store.py is the single command that turns the corpus into the
# trained store. It is the only GPU step in the whole book. The configuration
# below is copied verbatim from that script -- it is the reproducible recipe:
# a fixed geometry, a fixed training budget, and regex ingest (deterministic,
# no LLM in the extraction path). Running it twice produces the same store.
#
#   from knowlytix.core.config import GeometryConfig, TrainConfig
#   from knowlytix.knowledge.config import DocGMSConfig
#   from knowlytix.knowledge.geode.rag import build_rag_store
#   from knowlytix.knowledge.geode.loop import make_default_trainer
#
#   cfg = DocGMSConfig(
#       store_path="data/gms_annual_report_store",
#       ingest_mode="regex",                 # deterministic extraction
#       loss_mode="cap",
#       geometry=GeometryConfig(d_v=64, d_u=64, m=32, d=32),
#       train=TrainConfig(epochs=150, batch_size=64, neg_samples=16,
#                         lr=5e-3, lr_riemannian=2e-3),
#   )
#   res = build_rag_store("data/annual_report.md", cfg, device=dev,
#                         geode_trainer=make_default_trainer(dev, epochs=80))
#
# res is a RagBuildResult with: converged, iterations, n_entities, n_triples,
# n_enm, corrections, anchor_violations. build_store.py prints those, then
# regenerates data/corpus_facts.md from the trained store. DO NOT run this cell
# in a shared-GPU session; the lead runs `python scripts/build_store.py` in CI.
print("build_store.py is the GPU step; see scripts/build_store.py. Skipped here.")'''

BUILD_NB_DOC = '''\
# Notebooks are *built*, not edited by hand. Each scripts/build_nb_*.py emits one
# notebook with nbformat so the JSON is always valid and the first cell is always
# the exact KNOWLYTIX_SRC bootstrap. Re-running a builder regenerates its notebook
# deterministically; that is how a .tex listing stays byte-identical to the cell
# it documents. List the builders and the notebooks they own.
SCRIPTS = os.path.join(REPO_ROOT, "scripts")
builders = sorted(f for f in os.listdir(SCRIPTS)
                  if f.startswith(("build_nb", "build_notebook")))
print(f"{len(builders)} notebook builders:")
for b in builders:
    print(" ", b)'''

VERIFY_REPRO = '''\
# The reproducibility claim: a fresh clone's *shipped* store reproduces the
# corpus facts byte-exact. We load the store on CPU (cheap -- no GPU, no Qwen)
# and read three ENM figures back through lookup_enm. These are the exact values
# in data/corpus_facts.md; if a rebuild ever drifts, this cell fails first.
import torch
from knowlytix.knowledge.config import DocGMSConfig
from knowlytix.knowledge.store import GMSExpertStore

store = GMSExpertStore(DocGMSConfig(store_path=STORE),
                       device=torch.device("cpu"))
assert store.load(), f"no trained store at {STORE}; run scripts/build_store.py first"

# (category, entity_id, expected) -- verbatim from data/corpus_facts.md.
EXPECTED_ENM = [
    ("income_statement", "Revenue/FY2025", 355.0),
    ("segment_performance", "Cloud Platform/Technology/Revenue", 120.0),
    ("balance_sheet", "Total Assets", 540.0),
]
for category, entity_id, expected in EXPECTED_ENM:
    got = store.lookup_enm(category, entity_id)
    print(f"{category}/{entity_id} = {got}  (expected {expected})")
    assert got == expected, f"ENM drift: {category}/{entity_id} {got} != {expected}"
print("\\nstore reproduces the shipped corpus facts byte-exact")'''

SUM_ANCHOR = '''\
# A second reproduction invariant, independent of any single value: the segment
# revenues must sum to the Total row. This is the numeric *sum anchor* GEODE
# enforces during the build (Chapter 5); checking it here proves the shipped
# store is internally consistent, not just that one cell happens to match.
SEGMENTS = ["Cloud Platform/Technology", "Devices/Technology",
            "Logistics/Operations", "Retail/Operations"]
parts = [store.lookup_enm("segment_performance", f"{s}/Revenue") for s in SEGMENTS]
total = store.lookup_enm("segment_performance", "Total/All/Revenue")
print("segments:", parts, " sum:", sum(parts), " total:", total)
assert sum(parts) == total, f"sum anchor broken: {sum(parts)} != {total}"
print("sum anchor holds: Total = sum(segments)")'''

EXERCISE = '''\
# Exercise (worked): strengthen the reproduction check with a second sum anchor
# and a two-hop retrieval -- both CPU-only, both grounded in data/corpus_facts.md.
# (1) headcounts must sum to the Total row.
head_parts = [store.lookup_enm("segment_performance", f"{s}/Headcount")
              for s in SEGMENTS]
head_total = store.lookup_enm("segment_performance", "Total/All/Headcount")
assert sum(head_parts) == head_total == 1500.0
print("headcount anchor holds:", sum(head_parts), "==", head_total)

# (2) reproduce the two-hop retrieval: cloud platform -> division -> region.
from knowlytix.knowledge.geode.provenance import ProvenanceLedger
from knowlytix.knowledge.rag import Retriever, TripleBinder
from knowlytix.knowledge.rag.query_triples import QueryTriple

ledger = ProvenanceLedger.from_text(store.markdown)
binder = TripleBinder(store)
retriever = Retriever(store, ledger)
chain = [binder.bind(QueryTriple("cloud platform", "has_division", "?x")),
         binder.bind(QueryTriple("?x", "has_region", "?"))]
result = retriever.retrieve(chain)
print("two-hop answers:", result.answers)
assert any(a[0] == "north america" for a in result.answers)
print("two-hop retrieval reproduces: north america")'''

SELF_CHECK = '''\
# Self-check: the chapter's claim is that a fresh clone reproduces the artifacts.
# We assert the artifact tree is present, the store loads, every documented ENM
# value reads back exactly, and the sum anchor holds -- the same gates CI runs.
assert os.path.exists(STORE), "store directory missing"
assert store.lookup_enm("income_statement", "Revenue/FY2025") == 355.0
assert sum(store.lookup_enm("segment_performance", f"{s}/Revenue")
           for s in SEGMENTS) == store.lookup_enm("segment_performance",
                                                   "Total/All/Revenue")
print("App D self-check passed: artifacts reproduce byte-exact from a clone.")'''


def build() -> None:
    nb = new_notebook()
    nb.cells = [
        new_markdown_cell(
            "# Appendix D --- Reproducing the Artifacts\n"
            "\n"
            "One command rebuilds everything: `python scripts/build_store.py` turns "
            "the corpus into the trained store (the only GPU step), and the "
            "`scripts/build_nb_*.py` builders regenerate every notebook. This "
            "appendix documents that pipeline and proves the *shipped* store "
            "reproduces the corpus facts byte-exact -- on CPU, no Qwen, so a "
            "reader can verify a fresh clone before spending a GPU minute."
        ),
        new_code_cell(BOOTSTRAP),
        new_markdown_cell("## The artifact tree"),
        new_code_cell(LAYOUT),
        new_markdown_cell("## The trained store on disk"),
        new_code_cell(STORE_LAYOUT),
        new_markdown_cell("## The one GPU step: `build_store.py`"),
        new_code_cell(BUILD_STORE_DOC),
        new_markdown_cell("## Notebooks are built, not hand-edited"),
        new_code_cell(BUILD_NB_DOC),
        new_markdown_cell("## Verifying the reproduction (CPU only)"),
        new_code_cell(VERIFY_REPRO),
        new_code_cell(SUM_ANCHOR),
        new_markdown_cell("## Exercise (worked solution)"),
        new_code_cell(EXERCISE),
        new_markdown_cell("## Self-check"),
        new_code_cell(SELF_CHECK),
    ]
    nb.metadata = {
        "kernelspec": {"display_name": "Python 3", "language": "python",
                       "name": "python3"},
        "language_info": {"name": "python", "version": "3.12"},
    }
    with open(OUT, "w", encoding="utf-8") as f:
        nbf.write(nb, f)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    build()
