# SPDX-License-Identifier: Apache-2.0
"""Stage 1 of the build: GEODE self-correct the Annual Report into a trained
GMSExpertStore, and emit the ground-truth facts sheet (data/corpus_facts.md).

This builds only the STORE (corrected graph + cap geometry + ENM). The encoders
and the relevance gate are tuned downstream, on data GENERATED from this store:

    1. scripts/build_store.py        GeodeLoop -> store geometry + ENM   (this file)
    2. scripts/enrich_data.py        mine store -> DoE -> contextual training data
    3. scripts/finetune_encoders.py  v/u SFT on the generated data + calibration

Run:  python scripts/build_store.py
Uses the GMS-knowlytix branch library (see scripts/_bootstrap.py); override the
path with KNOWLYTIX_SRC.
"""

from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _bootstrap import KNOWLYTIX_SRC, REPO_ROOT, use_branch_library  # noqa: E402

use_branch_library()

import torch  # noqa: E402

from knowlytix.core.config import GeometryConfig, TrainConfig  # noqa: E402
from knowlytix.knowledge.config import DocGMSConfig  # noqa: E402
from knowlytix.knowledge.geode.loop import GeodeLoop, make_default_trainer  # noqa: E402
from knowlytix.knowledge.geode.provenance import ProvenanceLedger  # noqa: E402
from knowlytix.knowledge.geode.rag import (  # noqa: E402
    fact_only_triples, store_from_triples,
)
from knowlytix.knowledge.rag import (  # noqa: E402
    Retriever, TripleBinder, coverage_report, graph_coverage,
)
from knowlytix.knowledge.rag.query_triples import QueryTriple  # noqa: E402

MD = os.environ.get("GMS_MD", os.path.join(REPO_ROOT, "data", "annual_report.md"))
STORE = os.environ.get("GMS_STORE",
                       os.path.join(REPO_ROOT, "data", "gms_annual_report_store"))
FACTS = os.environ.get("GMS_FACTS", os.path.join(REPO_ROOT, "data", "corpus_facts.md"))


def main() -> None:
    dev = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    cfg = DocGMSConfig(
        store_path=STORE,
        ingest_mode="regex",
        loss_mode="cap",
        geometry=GeometryConfig(d_v=64, d_u=64, m=32, d=32),
        train=TrainConfig(epochs=150, batch_size=64, neg_samples=16,
                          lr=5e-3, lr_riemannian=2e-3),
    )
    print(f"KNOWLYTIX_SRC = {KNOWLYTIX_SRC}\nbuilding store from {MD} on {dev}")

    # 1) GEODE self-correction: propose -> diagnose (geometry + ENM + provenance)
    #    -> repair, yielding a corrected triple set.
    print("\n[1/3] GEODE self-correction loop")
    loop = GeodeLoop(make_default_trainer(dev, epochs=80), device=dev, max_iters=8)
    res = loop.run(MD)
    kept = fact_only_triples(res.triples)
    print(f"  converged={res.converged} iters={res.iterations} "
          f"corrections={len(res.corrections)} anchor_violations="
          f"{len(res.anchor_violations)} kept_triples={len(kept)}")

    # 2) train the production store (cap geometry + ENM) on the corrected graph.
    print("\n[2/3] train production store (cap geometry + ENM)")
    store = store_from_triples(MD, kept, cfg, dev)

    # Persist the geometry into model_dims.json so the store stays self-describing.
    # The library save omits it, and store.load() rebuilds the model from
    # config.geometry -- so a later load with a bare DocGMSConfig fails once the
    # library default geometry drifts (this store is d=32; the current default is
    # d=128). Writing it here lets load_store_geo recover the true geometry.
    dims_p = os.path.join(STORE, "model_dims.json")
    if os.path.isfile(dims_p):
        _md = json.load(open(dims_p))
        _g = cfg.geometry
        _md["geometry"] = {"d_v": _g.d_v, "d_u": _g.d_u, "m": _g.m, "d": _g.d}
        json.dump(_md, open(dims_p, "w"))

    # 3) coverage report (triple-mediation blind spots) beside the store.
    print("\n[3/3] coverage report")
    cov = coverage_report(store)
    gcov = graph_coverage(res.triples)
    with open(os.path.join(STORE, "coverage_report.json"), "w") as fh:
        json.dump({**cov.as_dict(), "graph": gcov.as_dict()}, fh, indent=2)
    print(f"  coverage_ratio={cov.coverage_ratio:.2f}")

    _emit_facts(store)
    print(f"\nwrote {FACTS}")


def _emit_facts(store) -> None:
    ledger = ProvenanceLedger.from_text(store.markdown)
    binder = TripleBinder(store)
    retr = Retriever(store, ledger)
    L: list[str] = ["# Corpus facts — Northwind Industries FY2025",
                    "",
                    "Ground truth for chapter authors. Generated by "
                    "`scripts/build_store.py` from the trained store. Use these "
                    "exact entity/relation names and values in listings.", ""]

    rels = sorted(store.adapter.relation_to_idx)
    L += ["## Relations", "", ", ".join(f"`{r}`" for r in rels), ""]

    L += ["## Sample triples (canonicalized)", ""]
    for h, r, t in store.triples[:40]:
        if r != "in_section":
            L.append(f"- `{h}` `{r}` `{t}`")
    L.append("")

    L += ["## Exact Numerical Memory (lookup_enm category/id = value)", ""]
    if store.enm is not None:
        for key in store.enm.keys():
            val = store.enm.read_exact(key)
            v = float(val.reshape(-1)[0]) if val is not None else None
            L.append(f"- `{key.type}` / `{key.id}` = {v}")
    L.append("")

    cov = coverage_report(store)
    L += ["## Coverage (triple-mediation blind spots)", "",
          f"coverage_ratio = {cov.coverage_ratio:.2f}", ""]
    for rg in cov.regions:
        flag = "  <-- BLIND SPOT" if rg.blind_spot else ""
        L.append(f"- [{'x' if rg.covered else ' '}] {rg.title} "
                 f"({rg.triple_count} triples, {rg.body_lines} body lines){flag}")
    L.append("")

    L += ["## Sample retrieval (no LLM — Retriever over bound query triples)", ""]
    # single-hop
    bt = binder.bind(QueryTriple("cloud platform", "has_revenue", "?"))
    r1 = retr.retrieve([bt])
    L.append(f"- Q: cloud platform revenue -> "
             f"{[(f.head, f.relation, f.tail, f.location) for f in r1.facts]}")
    # two-hop: segment -> division -> region
    chain = [binder.bind(QueryTriple("cloud platform", "has_division", "?x")),
             binder.bind(QueryTriple("?x", "has_region", "?"))]
    r2 = retr.retrieve(chain)
    L.append(f"- Q: region of cloud platform's division -> "
             f"answers={r2.answers}  facts={[(f.head, f.relation, f.tail) for f in r2.facts]}")
    L.append("")

    with open(FACTS, "w", encoding="utf-8") as f:
        f.write("\n".join(L))


if __name__ == "__main__":
    main()
